spring:
  properties:
    host-name: localhost
    github:
      token: ${GithubBearer}
    async:
      max-pool-size: 100
      core-pool-size: 20
  application:
      name: good-first-issue-back
  datasource:
    password: SomeUselessPassword02
    url: jdbc:postgresql://${spring.properties.host-name}:5432/uj?currentSchema=gfi
    username: idk_user
  jpa:
    hibernate:
      ddl-auto: update